### ISSUE TITLE
prefix initialization error when github is not present

### ISSUE THREAD

**Issue by eroux** [buda-base/bdrc-libraries#6]
the code should allow initialization from a lds-queries git repo instead of github [here](https://github.com/buda-base/bdrc-libraries/blob/master/src/main/java/io/bdrc/libraries/Prefixes.java#L38)

**Comment by eroux** [comment]
also [here](https://github.com/buda-base/bdrc-libraries/blob/6e1cc7cb83a8c2751b8c27c591b5cc7204fce95a/src/main/java/io/bdrc/libraries/formatters/JSONLDFormatter.java) and [here](https://github.com/buda-base/bdrc-libraries/blob/498e55875c86bc356cbd1b4851f5804efe78db71/src/main/java/io/bdrc/libraries/BDRCReasoner.java)

**Comment by MarcAgate** [comment]
fixed as of commit b28dedb
it's been deployed to maven central, installed on buda1 and buda3. Moreover, all services (ldspdi, iiifserv and iiifpres have been updated and redeployed)

**Comment by eroux** [comment]
ok, great!

**Comment by eroux** [comment]
what about https://github.com/buda-base/bdrc-libraries/blob/master/src/main/java/io/bdrc/libraries/BDRCReasoner.java#L256 ?

**Comment by MarcAgate** [comment]
Oops, didn't see it. I'll fix that too.
